# Generated by Django 4.1.7 on 2023-03-21 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lessname', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Предметы',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(default=None)),
                ('grade', models.IntegerField(default=None, max_length=1)),
                ('lessons', models.ManyToManyField(blank=True, related_name='less', to='schclass.lesson')),
            ],
            options={
                'verbose_name': 'Ученики',
            },
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom', models.CharField(max_length=100)),
                ('year_of_learning', models.IntegerField(default=None)),
                ('students', models.ManyToManyField(blank=True, related_name='stud', to='schclass.student')),
            ],
            options={
                'verbose_name': 'Журнал',
            },
        ),
    ]
